/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExampleButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'left'
         */
        "iconAlign": 'left' | 'right';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLExampleButtonElement extends Components.ExampleButton, HTMLStencilElement {
    }
    var HTMLExampleButtonElement: {
        prototype: HTMLExampleButtonElement;
        new (): HTMLExampleButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "example-button": HTMLExampleButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ExampleButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'left'
         */
        "iconAlign"?: 'left' | 'right';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "example-button": ExampleButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "example-button": LocalJSX.ExampleButton & JSXBase.HTMLAttributes<HTMLExampleButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
